/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppSupportStaffRouteImport } from './routes/_app/support-staff'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSalaryRouteImport } from './routes/_app/salary'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppRouletteRouteImport } from './routes/_app/roulette'
import { Route as AppNormsRouteImport } from './routes/_app/norms'
import { Route as AppModeratorStaffRouteImport } from './routes/_app/moderator-staff'
import { Route as AppModeratorShiftsRouteImport } from './routes/_app/moderator-shifts'
import { Route as AppMeetingsRouteImport } from './routes/_app/meetings'
import { Route as AppHelperStaffRouteImport } from './routes/_app/helper-staff'
import { Route as AppEventsmodStaffRouteImport } from './routes/_app/eventsmod-staff'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCouplesRouteImport } from './routes/_app/couples'
import { Route as AppControlStaffRouteImport } from './routes/_app/control-staff'
import { Route as AppContent_makerStaffRouteImport } from './routes/_app/content_maker-staff'
import { Route as AppClosemodStaffRouteImport } from './routes/_app/closemod-staff'
import { Route as AppBlacklistRouteImport } from './routes/_app/blacklist'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportStaffRoute = AppSupportStaffRouteImport.update({
  id: '/support-staff',
  path: '/support-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppRouletteRoute = AppRouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => AppRoute,
} as any)
const AppNormsRoute = AppNormsRouteImport.update({
  id: '/norms',
  path: '/norms',
  getParentRoute: () => AppRoute,
} as any)
const AppModeratorStaffRoute = AppModeratorStaffRouteImport.update({
  id: '/moderator-staff',
  path: '/moderator-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppModeratorShiftsRoute = AppModeratorShiftsRouteImport.update({
  id: '/moderator-shifts',
  path: '/moderator-shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppHelperStaffRoute = AppHelperStaffRouteImport.update({
  id: '/helper-staff',
  path: '/helper-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsmodStaffRoute = AppEventsmodStaffRouteImport.update({
  id: '/eventsmod-staff',
  path: '/eventsmod-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCouplesRoute = AppCouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => AppRoute,
} as any)
const AppControlStaffRoute = AppControlStaffRouteImport.update({
  id: '/control-staff',
  path: '/control-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppContent_makerStaffRoute = AppContent_makerStaffRouteImport.update({
  id: '/content_maker-staff',
  path: '/content_maker-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppClosemodStaffRoute = AppClosemodStaffRouteImport.update({
  id: '/closemod-staff',
  path: '/closemod-staff',
  getParentRoute: () => AppRoute,
} as any)
const AppBlacklistRoute = AppBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/blacklist': typeof AppBlacklistRoute
  '/closemod-staff': typeof AppClosemodStaffRoute
  '/content_maker-staff': typeof AppContent_makerStaffRoute
  '/control-staff': typeof AppControlStaffRoute
  '/couples': typeof AppCouplesRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventsmod-staff': typeof AppEventsmodStaffRoute
  '/helper-staff': typeof AppHelperStaffRoute
  '/meetings': typeof AppMeetingsRoute
  '/moderator-shifts': typeof AppModeratorShiftsRoute
  '/moderator-staff': typeof AppModeratorStaffRoute
  '/norms': typeof AppNormsRoute
  '/roulette': typeof AppRouletteRoute
  '/rules': typeof AppRulesRoute
  '/salary': typeof AppSalaryRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/support-staff': typeof AppSupportStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/blacklist': typeof AppBlacklistRoute
  '/closemod-staff': typeof AppClosemodStaffRoute
  '/content_maker-staff': typeof AppContent_makerStaffRoute
  '/control-staff': typeof AppControlStaffRoute
  '/couples': typeof AppCouplesRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventsmod-staff': typeof AppEventsmodStaffRoute
  '/helper-staff': typeof AppHelperStaffRoute
  '/meetings': typeof AppMeetingsRoute
  '/moderator-shifts': typeof AppModeratorShiftsRoute
  '/moderator-staff': typeof AppModeratorStaffRoute
  '/norms': typeof AppNormsRoute
  '/roulette': typeof AppRouletteRoute
  '/rules': typeof AppRulesRoute
  '/salary': typeof AppSalaryRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/support-staff': typeof AppSupportStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/blacklist': typeof AppBlacklistRoute
  '/_app/closemod-staff': typeof AppClosemodStaffRoute
  '/_app/content_maker-staff': typeof AppContent_makerStaffRoute
  '/_app/control-staff': typeof AppControlStaffRoute
  '/_app/couples': typeof AppCouplesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eventsmod-staff': typeof AppEventsmodStaffRoute
  '/_app/helper-staff': typeof AppHelperStaffRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/moderator-shifts': typeof AppModeratorShiftsRoute
  '/_app/moderator-staff': typeof AppModeratorStaffRoute
  '/_app/norms': typeof AppNormsRoute
  '/_app/roulette': typeof AppRouletteRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/salary': typeof AppSalaryRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/support-staff': typeof AppSupportStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/blacklist'
    | '/closemod-staff'
    | '/content_maker-staff'
    | '/control-staff'
    | '/couples'
    | '/dashboard'
    | '/eventsmod-staff'
    | '/helper-staff'
    | '/meetings'
    | '/moderator-shifts'
    | '/moderator-staff'
    | '/norms'
    | '/roulette'
    | '/rules'
    | '/salary'
    | '/schedule'
    | '/settings'
    | '/staff'
    | '/support-staff'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/blacklist'
    | '/closemod-staff'
    | '/content_maker-staff'
    | '/control-staff'
    | '/couples'
    | '/dashboard'
    | '/eventsmod-staff'
    | '/helper-staff'
    | '/meetings'
    | '/moderator-shifts'
    | '/moderator-staff'
    | '/norms'
    | '/roulette'
    | '/rules'
    | '/salary'
    | '/schedule'
    | '/settings'
    | '/staff'
    | '/support-staff'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/blacklist'
    | '/_app/closemod-staff'
    | '/_app/content_maker-staff'
    | '/_app/control-staff'
    | '/_app/couples'
    | '/_app/dashboard'
    | '/_app/eventsmod-staff'
    | '/_app/helper-staff'
    | '/_app/meetings'
    | '/_app/moderator-shifts'
    | '/_app/moderator-staff'
    | '/_app/norms'
    | '/_app/roulette'
    | '/_app/rules'
    | '/_app/salary'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/support-staff'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/support-staff': {
      id: '/_app/support-staff'
      path: '/support-staff'
      fullPath: '/support-staff'
      preLoaderRoute: typeof AppSupportStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary': {
      id: '/_app/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roulette': {
      id: '/_app/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof AppRouletteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/norms': {
      id: '/_app/norms'
      path: '/norms'
      fullPath: '/norms'
      preLoaderRoute: typeof AppNormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderator-staff': {
      id: '/_app/moderator-staff'
      path: '/moderator-staff'
      fullPath: '/moderator-staff'
      preLoaderRoute: typeof AppModeratorStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderator-shifts': {
      id: '/_app/moderator-shifts'
      path: '/moderator-shifts'
      fullPath: '/moderator-shifts'
      preLoaderRoute: typeof AppModeratorShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/helper-staff': {
      id: '/_app/helper-staff'
      path: '/helper-staff'
      fullPath: '/helper-staff'
      preLoaderRoute: typeof AppHelperStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventsmod-staff': {
      id: '/_app/eventsmod-staff'
      path: '/eventsmod-staff'
      fullPath: '/eventsmod-staff'
      preLoaderRoute: typeof AppEventsmodStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/couples': {
      id: '/_app/couples'
      path: '/couples'
      fullPath: '/couples'
      preLoaderRoute: typeof AppCouplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control-staff': {
      id: '/_app/control-staff'
      path: '/control-staff'
      fullPath: '/control-staff'
      preLoaderRoute: typeof AppControlStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content_maker-staff': {
      id: '/_app/content_maker-staff'
      path: '/content_maker-staff'
      fullPath: '/content_maker-staff'
      preLoaderRoute: typeof AppContent_makerStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/closemod-staff': {
      id: '/_app/closemod-staff'
      path: '/closemod-staff'
      fullPath: '/closemod-staff'
      preLoaderRoute: typeof AppClosemodStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blacklist': {
      id: '/_app/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof AppBlacklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBlacklistRoute: typeof AppBlacklistRoute
  AppClosemodStaffRoute: typeof AppClosemodStaffRoute
  AppContent_makerStaffRoute: typeof AppContent_makerStaffRoute
  AppControlStaffRoute: typeof AppControlStaffRoute
  AppCouplesRoute: typeof AppCouplesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsmodStaffRoute: typeof AppEventsmodStaffRoute
  AppHelperStaffRoute: typeof AppHelperStaffRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppModeratorShiftsRoute: typeof AppModeratorShiftsRoute
  AppModeratorStaffRoute: typeof AppModeratorStaffRoute
  AppNormsRoute: typeof AppNormsRoute
  AppRouletteRoute: typeof AppRouletteRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSupportStaffRoute: typeof AppSupportStaffRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBlacklistRoute: AppBlacklistRoute,
  AppClosemodStaffRoute: AppClosemodStaffRoute,
  AppContent_makerStaffRoute: AppContent_makerStaffRoute,
  AppControlStaffRoute: AppControlStaffRoute,
  AppCouplesRoute: AppCouplesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsmodStaffRoute: AppEventsmodStaffRoute,
  AppHelperStaffRoute: AppHelperStaffRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppModeratorShiftsRoute: AppModeratorShiftsRoute,
  AppModeratorStaffRoute: AppModeratorStaffRoute,
  AppNormsRoute: AppNormsRoute,
  AppRouletteRoute: AppRouletteRoute,
  AppRulesRoute: AppRulesRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppSupportStaffRoute: AppSupportStaffRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
